version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: api/docker/php/Dockerfile
    container_name: sido-php
    volumes:
      - ./:/srv/api:cached
    environment:
      APP_ENV: dev
      PHP_IDE_CONFIG: "serverName=sido"
      DATABASE_URL: postgresql://symfony:symfony@database:5432/app?serverVersion=15&charset=utf8
      MERCURE_URL: http://mercure/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost:3000/.well-known/mercure
      MERCURE_JWT_SECRET: '!ChangeMe!'
    depends_on:
      database:
        condition: service_healthy
      mercure:
        condition: service_started
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: api/docker/nginx/Dockerfile
    container_name: sido-nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/srv/api:cached
      - nginx-cache:/var/cache/nginx
    networks:
      - backend

  database:
    image: postgres:15-alpine
    container_name: sido-postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "symfony"]
      interval: 5s
      timeout: 5s
      retries: 5

  mercure:
    image: dunglas/mercure:latest
    container_name: sido-mercure
    environment:
      SERVER_NAME: ':80'
      JWT_KEY: '!ChangeMe!'
      ALLOW_ANONYMOUS: "1"
      CORS_ALLOWED_ORIGINS: "*"
      PUBLISH_ALLOWED_ORIGINS: "*"
      MERCURE_SUBSCRIBE_ALLOWED_ORIGINS: "*"
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    ports:
      - "3000:80"
    networks:
      - backend

  frontend:
    image: node:18
    container_name: sido-frontend
    working_dir: /app
    command: sh -c "if [ -f package.json ]; then npm install && npm run start; else echo 'No Angular project detected - sleeping' && tail -f /dev/null; fi"
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - php
    networks:
      - backend

volumes:
  postgres-data:
  nginx-cache:

networks:
  backend:
    driver: bridge
